### ISSUE TITLE
support just major.minor?

### ISSUE THREAD

**Issue by drdamour** [isen-ng/homebrew-dotnet-sdk-versions#156]
i'd like to be able to just 
```
brew install -cask dotnet-sdk3-1
```

and get the latest 3.1

and support for brew upgrade --cask (maybe --greeedy) to get the latests

**Comment by isen-ng** [comment]
Hmm what is your use case? I'm trying to understand if this is a use-case this repo should support.

The current use-case is to let user install any version they want. There is no "upgrade" because installing a new (or higher) version simply installs it side-by-side with the existing sdk. This behaviour is dictated by dotnet-sdk and is something we cannot control in this repository.

The only upgrade supported by dotnet-sdk is the build version.

**Comment by drdamour** [comment]
Yup and its that build version i always want the latest of.  They recently
switched the devops agents to always build with the latest build version of
the major minor by ONLY having the latest build version on any agent so
many of us are now always building with the latest build number of major
minor in our pipelines by default.  Want local to be the same.

https://docs.microsoft.com/en-us/azure/devops/release-notes/2021/sprint-190-update#change-in-net-sdk-preinstallation-policy-on-microsoft-hosted-windows-and-macos-agents

**Comment by isen-ng** [comment]
Hmm, according to the article you linked 

> The SDK version is composed of the following parts: x.y.znn. z is the feature version and nn is the patch version. For example, for 2.1.302, the feature version is 3, and 02 is the patch version. According to the new approach, we will only install the latest patch version for every feature version, i.e. only 2.1.302 will be installed for 2.1.3x, only 2.1.403 for 2.1.4x and so on.

This means that hosted agents care about `major.minor.feature`, instead of only `major.minor` described in your original request. The change to hosted agents is what currently this repo supports.

**Comment by drdamour** [comment]
well i guess i should RTFM then ;)

just so i fully understand, dotnet-sdk3-1-400 currently installs dotnet 3.1.412  if dotnet sdk 3.1.413 comes out, how to i "upgrade" to that with this tap?

**Comment by isen-ng** [comment]
sorry for the late response.

I believe that is the case. However, I cannot confirm this behavior for you at this moment as I have no access to a mac (current employer insisted to furnish me with a Windows).

I'll leave this ticket open, and I'll report back once I can confirm the behavior.

**Comment by isen-ng** [comment]
Sorry for the long wait. Do this to upgrade from `3.1.412` to `3.1.413`.

Assuming that the casks have been updated with `3.1.413`, and you have `3.1.412` installed,

1. `brew update`
    - this will update the casks that are cloned to your local
2. `brew upgrade --cask dotnet-sdk3-1-400`
    - this will install `3.1.413` to your system
3. Done

It doesn't matter if `3.1.412` is not removed on your system. The `dotnet` executable will automatically choose the highest patch version that matches the framework version you chose for your project.

If you specifically want to use `3.1.412` instead of `3.1.413`, you'll need to use [global.json](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x) to specify that.
