### ISSUE TITLE
Needing sudo permissions

### ISSUE THREAD

**Issue by Curs3W4ll** [isen-ng/homebrew-dotnet-sdk-versions#284]
Hi!

Just wonder why the `dotnet` CLI needs permissions when installed with this cask (`dotnet-sdk7-0-400 ` in my case)?

<img width="530" alt="Screenshot 2023-09-22 at 11 25 48" src="https://github.com/isen-ng/homebrew-dotnet-sdk-versions/assets/72013831/bffe3be8-d7a5-41e3-8b28-250c18b94a17">

On the other hand, the `dotnet` CLI from Formulae doesn't need these permissions (but latest version is `7.0.100`)

**Comment by isen-ng** [comment]
Let me check

**Comment by isen-ng** [comment]
I think this probably an inherent thing with "casks".

Casks download the `pkg` file from Microsoft and installs it. Whereas formulae downloads the source code and compiles them. I'm not exactly sure what the difference is, but I think even the official dotnet cask suffers the same problem.

I am away from my laptop these few days due to personal matters, but you should be able to install the official dotnet cask (not the formula) by running `brew install --cask dotnet-sdk` and that should suffer the same sudo requirement problem.

I'll test this myself when I get back to my laptop

**Comment by Curs3W4ll** [comment]
@isen-ng Yes, that's right, the official dotnet-sdk of Microsoft suffers from that problem too.

Your explanation clarified my comprehension of how this works, and it makes sense that the cask suffers from that problem too as the official Microsoft SDK download has it.

Thanks for your fast reply!, I look on over the Microsoft side 😬
